version: "3.8"

services:
  db:
    container_name: GitInsight-db
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Dev@password
    ports:
      - 1431:1431
    restart: always
  api:
    container_name: GitInsight-api
    build: ./
    volumes:
      - ./:/app
    ports:
      - 8090:8090
      - 8443:8443
    restart: always
    environment:
      - ASPNETCORE_Kestrel__Certificates__Development__Password="Dev@password"
    depends_on:
      - db
