// <auto-generated />
using System;
using GitInsight.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GitInsight.Entities.Migrations
{
    [DbContext(typeof(GitInsightContext))]
    [Migration("20221104115759_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("GitInsight.Entities.DBAnalysis_s", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<int>("CommitID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitRepository")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DBAnalysis_s");
                });

            modelBuilder.Entity("GitInsight.Entities.DBFrequency", b =>
                {
                    b.Property<int>("DBAnalysis_sId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.HasKey("DBAnalysis_sId", "Date");

                    b.ToTable("DBFrequency");
                });

            modelBuilder.Entity("GitInsight.Entities.DBFrequency", b =>
                {
                    b.HasOne("GitInsight.Entities.DBAnalysis_s", "DBAnalysis_s")
                        .WithMany("Frequencies")
                        .HasForeignKey("DBAnalysis_sId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DBAnalysis_s");
                });

            modelBuilder.Entity("GitInsight.Entities.DBAnalysis_s", b =>
                {
                    b.Navigation("Frequencies");
                });
#pragma warning restore 612, 618
        }
    }
}
