global using GitInsight;
global using NSubstitute;
global using LibGit2Sharp;
global using Xunit;
global using FluentAssertions;
global using GitInsight.Entities;
global using GitInsight.Core;
global using static GitInsight.Core.Response;
global using Microsoft.Data.Sqlite;
global using Microsoft.EntityFrameworkCore;